import { readFileSync, writeFileSync } from 'fs';

const existing = JSON.parse(readFileSync('./faro_AI_web_research_agent/target_cities.json', 'utf8'));

const african = [
  // North Africa
  { city:'Algiers',       country:'Algeria',                  govUrl:'https://www.andi.dz/',                             chamberUrl:'https://www.caci.dz/',              ecosystemUrl:'https://www.andi.dz/',                grantUrl:'https://www.andi.dz/',               numbeoCity:'Algiers' },
  { city:'Cairo',         country:'Egypt',                    govUrl:'https://www.gafi.gov.eg/',                         chamberUrl:'https://www.fedcoc.org.eg/',         ecosystemUrl:'https://www.cairo.gov.eg/',           grantUrl:'https://www.gafi.gov.eg/',           numbeoCity:'Cairo' },
  { city:'Tripoli',       country:'Libya',                    govUrl:'https://www.libyanboc.ly/',                        chamberUrl:'https://www.libyanboc.ly/',          ecosystemUrl:'https://www.libyanboc.ly/',           grantUrl:'https://www.libyanboc.ly/',          numbeoCity:'Tripoli' },
  { city:'Casablanca',    country:'Morocco',                  govUrl:'https://www.invest.gov.ma/',                       chamberUrl:'https://www.cgem.ma/',               ecosystemUrl:'https://www.cfcim.org/',              grantUrl:'https://www.invest.gov.ma/',         numbeoCity:'Casablanca' },
  { city:'Khartoum',      country:'Sudan',                    govUrl:'https://www.sudaneseinvestment.org/',               chamberUrl:'https://www.sudanchamber.org/',      ecosystemUrl:'https://www.sudaneseinvestment.org/', grantUrl:'https://www.sudaneseinvestment.org/', numbeoCity:'Khartoum' },
  { city:'Tunis',         country:'Tunisia',                  govUrl:'https://www.investintunisia.tn/',                  chamberUrl:'https://www.utica.org.tn/',          ecosystemUrl:'https://www.investintunisia.tn/',     grantUrl:'https://www.investintunisia.tn/',    numbeoCity:'Tunis' },
  // West Africa
  { city:'Cotonou',       country:'Benin',                    govUrl:'https://www.apiex.bj/',                            chamberUrl:'https://www.ccib.bj/',               ecosystemUrl:'https://www.apiex.bj/',               grantUrl:'https://www.apiex.bj/',              numbeoCity:'Cotonou' },
  { city:'Ouagadougou',   country:'Burkina Faso',             govUrl:'https://www.api.bf/',                              chamberUrl:'https://www.ccia.bf/',               ecosystemUrl:'https://www.api.bf/',                 grantUrl:'https://www.api.bf/',                numbeoCity:'Ouagadougou' },
  { city:'Praia',         country:'Cabo Verde',               govUrl:'https://www.cvtradeinvest.com/',                   chamberUrl:'https://www.cvtradeinvest.com/',     ecosystemUrl:'https://www.cvtradeinvest.com/',      grantUrl:'https://www.cvtradeinvest.com/',     numbeoCity:'Praia' },
  { city:'Abidjan',       country:"Cote d'Ivoire",            govUrl:'https://www.cepici.gouv.ci/',                      chamberUrl:'https://www.cci.ci/',                ecosystemUrl:'https://www.cepici.gouv.ci/',         grantUrl:'https://www.cepici.gouv.ci/',        numbeoCity:'Abidjan' },
  { city:'Serekunda',     country:'Gambia',                   govUrl:'https://www.gipa.gm/',                             chamberUrl:'https://www.gccinc.gm/',             ecosystemUrl:'https://www.gipa.gm/',                grantUrl:'https://www.gipa.gm/',               numbeoCity:'Banjul' },
  { city:'Accra',         country:'Ghana',                    govUrl:'https://www.gipcghana.com/',                       chamberUrl:'https://www.ghanachamber.org/',      ecosystemUrl:'https://www.myjoyonline.com/',        grantUrl:'https://www.gipcghana.com/',         numbeoCity:'Accra' },
  { city:'Conakry',       country:'Guinea',                   govUrl:'https://www.apip-guinee.com/',                     chamberUrl:'https://www.ccig.net/',              ecosystemUrl:'https://www.apip-guinee.com/',        grantUrl:'https://www.apip-guinee.com/',       numbeoCity:'Conakry' },
  { city:'Bissau',        country:'Guinea-Bissau',            govUrl:'https://www.africaneconomicoutlook.org/',           chamberUrl:'https://www.africaneconomicoutlook.org/', ecosystemUrl:'https://www.africaneconomicoutlook.org/', grantUrl:'https://www.africaneconomicoutlook.org/', numbeoCity:'Bissau' },
  { city:'Monrovia',      country:'Liberia',                  govUrl:'https://www.ncia.gov.lr/',                         chamberUrl:'https://www.liberiachamber.org/',    ecosystemUrl:'https://www.ncia.gov.lr/',            grantUrl:'https://www.ncia.gov.lr/',           numbeoCity:'Monrovia' },
  { city:'Bamako',        country:'Mali',                     govUrl:'https://www.apim.ml/',                             chamberUrl:'https://www.ccim.ml/',               ecosystemUrl:'https://www.apim.ml/',                grantUrl:'https://www.apim.ml/',               numbeoCity:'Bamako' },
  { city:'Nouakchott',    country:'Mauritania',               govUrl:'https://www.apim.mr/',                             chamberUrl:'https://www.cciam.mr/',              ecosystemUrl:'https://www.apim.mr/',                grantUrl:'https://www.apim.mr/',               numbeoCity:'Nouakchott' },
  { city:'Niamey',        country:'Niger',                    govUrl:'https://www.anipexport.ne/',                       chamberUrl:'https://www.ccin.ne/',               ecosystemUrl:'https://www.anipexport.ne/',          grantUrl:'https://www.anipexport.ne/',         numbeoCity:'Niamey' },
  { city:'Lagos',         country:'Nigeria',                  govUrl:'https://www.nigerianinvestmentpromotioncommission.gov.ng/', chamberUrl:'https://www.naccima.com/', ecosystemUrl:'https://www.cchub.xyz/',             grantUrl:'https://www.nigerianinvestmentpromotioncommission.gov.ng/', numbeoCity:'Lagos' },
  { city:'Sao Tome',      country:'Sao Tome and Principe',    govUrl:'https://www.africaneconomicoutlook.org/',           chamberUrl:'https://www.africaneconomicoutlook.org/', ecosystemUrl:'https://www.africaneconomicoutlook.org/', grantUrl:'https://www.africaneconomicoutlook.org/', numbeoCity:'Sao Tome' },
  { city:'Dakar',         country:'Senegal',                  govUrl:'https://www.investinsenegal.com/',                 chamberUrl:'https://www.cciad.sn/',              ecosystemUrl:'https://www.investinsenegal.com/',    grantUrl:'https://www.investinsenegal.com/',   numbeoCity:'Dakar' },
  { city:'Freetown',      country:'Sierra Leone',             govUrl:'https://www.sierraleone-invest.com/',              chamberUrl:'https://www.slcci.org/',             ecosystemUrl:'https://www.sierraleone-invest.com/', grantUrl:'https://www.sierraleone-invest.com/', numbeoCity:'Freetown' },
  { city:'Lome',          country:'Togo',                     govUrl:'https://www.api.tg/',                              chamberUrl:'https://www.cciag.tg/',              ecosystemUrl:'https://www.api.tg/',                 grantUrl:'https://www.api.tg/',                numbeoCity:'Lome' },
  // East Africa
  { city:'Bujumbura',     country:'Burundi',                  govUrl:'https://www.api.bi/',                              chamberUrl:'https://www.api.bi/',                ecosystemUrl:'https://www.api.bi/',                 grantUrl:'https://www.api.bi/',                numbeoCity:'Bujumbura' },
  { city:'Moroni',        country:'Comoros',                  govUrl:'https://www.africaneconomicoutlook.org/',           chamberUrl:'https://www.africaneconomicoutlook.org/', ecosystemUrl:'https://www.africaneconomicoutlook.org/', grantUrl:'https://www.africaneconomicoutlook.org/', numbeoCity:'Moroni' },
  { city:'Djibouti City', country:'Djibouti',                 govUrl:'https://www.investindjibouti.com/',                chamberUrl:'https://www.ccid.dj/',               ecosystemUrl:'https://www.investindjibouti.com/',   grantUrl:'https://www.investindjibouti.com/',  numbeoCity:'Djibouti' },
  { city:'Asmara',        country:'Eritrea',                  govUrl:'https://www.eritreainvestment.com/',               chamberUrl:'https://www.eritreainvestment.com/', ecosystemUrl:'https://www.eritreainvestment.com/', grantUrl:'https://www.eritreainvestment.com/', numbeoCity:'Asmara' },
  { city:'Addis Ababa',   country:'Ethiopia',                 govUrl:'https://www.ethiopiainvestment.gov.et/',           chamberUrl:'https://www.ethiopianchamber.com/', ecosystemUrl:'https://www.iceaddis.com/',           grantUrl:'https://www.ethiopiainvestment.gov.et/', numbeoCity:'Addis Ababa' },
  { city:'Nairobi',       country:'Kenya',                    govUrl:'https://www.investkenya.com/',                     chamberUrl:'https://www.kenyachamber.or.ke/',    ecosystemUrl:'https://www.ilabafrica.ac.ke/',       grantUrl:'https://www.investkenya.com/',       numbeoCity:'Nairobi' },
  { city:'Antananarivo',  country:'Madagascar',               govUrl:'https://www.edbm.mg/',                             chamberUrl:'https://www.ccifm.mg/',              ecosystemUrl:'https://www.edbm.mg/',                grantUrl:'https://www.edbm.mg/',               numbeoCity:'Antananarivo' },
  { city:'Port Louis',    country:'Mauritius',                govUrl:'https://www.edbmauritius.org/',                    chamberUrl:'https://www.mcci.org/',              ecosystemUrl:'https://www.edbmauritius.org/',       grantUrl:'https://www.edbmauritius.org/',      numbeoCity:'Port Louis' },
  { city:'Kigali',        country:'Rwanda',                   govUrl:'https://rdb.rw/',                                  chamberUrl:'https://www.rca.rw/',                ecosystemUrl:'https://www.klab.rw/',                grantUrl:'https://rdb.rw/',                    numbeoCity:'Kigali' },
  { city:'Victoria',      country:'Seychelles',               govUrl:'https://www.investseychelles.com/',                chamberUrl:'https://www.seychelleschamber.com/', ecosystemUrl:'https://www.investseychelles.com/',  grantUrl:'https://www.investseychelles.com/',  numbeoCity:'Victoria' },
  { city:'Mogadishu',     country:'Somalia',                  govUrl:'https://somaligov.net/',                           chamberUrl:'https://somalichamber.org/',         ecosystemUrl:'https://somaligov.net/',              grantUrl:'https://somaligov.net/',             numbeoCity:'Mogadishu' },
  { city:'Juba',          country:'South Sudan',              govUrl:'https://www.ipa.gov.ss/',                          chamberUrl:'https://www.ipa.gov.ss/',            ecosystemUrl:'https://www.ipa.gov.ss/',             grantUrl:'https://www.ipa.gov.ss/',            numbeoCity:'Juba' },
  { city:'Dar es Salaam', country:'Tanzania',                 govUrl:'https://www.tic.go.tz/',                           chamberUrl:'https://www.tccia.com/',             ecosystemUrl:'https://www.buni.or.tz/',             grantUrl:'https://www.tic.go.tz/',             numbeoCity:'Dar es Salaam' },
  { city:'Kampala',       country:'Uganda',                   govUrl:'https://www.ugandainvest.go.ug/',                  chamberUrl:'https://www.chamberuganda.com/',     ecosystemUrl:'https://hivecolab.org/',              grantUrl:'https://www.ugandainvest.go.ug/',    numbeoCity:'Kampala' },
  // Central Africa
  { city:'Douala',        country:'Cameroon',                 govUrl:'https://www.apip-cameroun.cm/',                    chamberUrl:'https://www.ccima.net/',             ecosystemUrl:'https://www.apip-cameroun.cm/',       grantUrl:'https://www.apip-cameroun.cm/',      numbeoCity:'Douala' },
  { city:'Bangui',        country:'Central African Republic', govUrl:'https://www.africaneconomicoutlook.org/',           chamberUrl:'https://www.africaneconomicoutlook.org/', ecosystemUrl:'https://www.africaneconomicoutlook.org/', grantUrl:'https://www.africaneconomicoutlook.org/', numbeoCity:'Bangui' },
  { city:'Ndjamena',      country:'Chad',                     govUrl:'https://www.anpi-tchad.td/',                       chamberUrl:'https://www.cciat.td/',              ecosystemUrl:'https://www.anpi-tchad.td/',          grantUrl:'https://www.anpi-tchad.td/',         numbeoCity:'Ndjamena' },
  { city:'Kinshasa',      country:'DR Congo',                 govUrl:'https://www.anapi.cd/',                            chamberUrl:'https://www.fec.cd/',                ecosystemUrl:'https://www.anapi.cd/',               grantUrl:'https://www.anapi.cd/',              numbeoCity:'Kinshasa' },
  { city:'Malabo',        country:'Equatorial Guinea',        govUrl:'https://www.africaneconomicoutlook.org/',           chamberUrl:'https://www.africaneconomicoutlook.org/', ecosystemUrl:'https://www.africaneconomicoutlook.org/', grantUrl:'https://www.africaneconomicoutlook.org/', numbeoCity:'Malabo' },
  { city:'Libreville',    country:'Gabon',                    govUrl:'https://www.agip.ga/',                             chamberUrl:'https://www.ccig.ga/',               ecosystemUrl:'https://www.agip.ga/',                grantUrl:'https://www.agip.ga/',               numbeoCity:'Libreville' },
  { city:'Pointe-Noire',  country:'Republic of the Congo',    govUrl:'https://www.api-congo.com/',                       chamberUrl:'https://www.ccic.cg/',               ecosystemUrl:'https://www.api-congo.com/',          grantUrl:'https://www.api-congo.com/',         numbeoCity:'Pointe-Noire' },
  // Southern Africa
  { city:'Luanda',        country:'Angola',                   govUrl:'https://www.aipex.gov.ao/',                        chamberUrl:'https://www.ccia.ao/',               ecosystemUrl:'https://www.aipex.gov.ao/',           grantUrl:'https://www.aipex.gov.ao/',          numbeoCity:'Luanda' },
  { city:'Gaborone',      country:'Botswana',                 govUrl:'https://www.bitc.co.bw/',                          chamberUrl:'https://www.boccim.co.bw/',          ecosystemUrl:'https://www.bitc.co.bw/',             grantUrl:'https://www.bitc.co.bw/',            numbeoCity:'Gaborone' },
  { city:'Manzini',       country:'Eswatini',                 govUrl:'https://www.sipa.org.sz/',                         chamberUrl:'https://www.sipa.org.sz/',           ecosystemUrl:'https://www.sipa.org.sz/',            grantUrl:'https://www.sipa.org.sz/',           numbeoCity:'Manzini' },
  { city:'Maseru',        country:'Lesotho',                  govUrl:'https://www.lndc.org.ls/',                         chamberUrl:'https://www.lcci.org.ls/',           ecosystemUrl:'https://www.lndc.org.ls/',            grantUrl:'https://www.lndc.org.ls/',           numbeoCity:'Maseru' },
  { city:'Blantyre',      country:'Malawi',                   govUrl:'https://www.malawibusiness.org/',                  chamberUrl:'https://www.mccci.org/',             ecosystemUrl:'https://www.malawibusiness.org/',     grantUrl:'https://www.malawibusiness.org/',    numbeoCity:'Blantyre' },
  { city:'Maputo',        country:'Mozambique',               govUrl:'https://www.apiex.gov.mz/',                        chamberUrl:'https://www.ccm.mz/',                ecosystemUrl:'https://www.apiex.gov.mz/',           grantUrl:'https://www.apiex.gov.mz/',          numbeoCity:'Maputo' },
  { city:'Windhoek',      country:'Namibia',                  govUrl:'https://www.namibiainvestment.com.na/',            chamberUrl:'https://www.ncci.org.na/',           ecosystemUrl:'https://www.namibiainvestment.com.na/', grantUrl:'https://www.namibiainvestment.com.na/', numbeoCity:'Windhoek' },
  { city:'Johannesburg',  country:'South Africa',             govUrl:'https://www.investsouthafrica.co.za/',             chamberUrl:'https://www.jcci.co.za/',            ecosystemUrl:'https://www.tia.org.za/',             grantUrl:'https://www.investsouthafrica.co.za/', numbeoCity:'Johannesburg' },
  { city:'Lusaka',        country:'Zambia',                   govUrl:'https://www.zda.org.zm/',                          chamberUrl:'https://www.zambiachamber.com/',     ecosystemUrl:'https://www.bongohive.co.zm/',        grantUrl:'https://www.zda.org.zm/',            numbeoCity:'Lusaka' },
  { city:'Harare',        country:'Zimbabwe',                 govUrl:'https://www.zimtrade.co.zw/',                      chamberUrl:'https://www.zncc.co.zw/',            ecosystemUrl:'https://www.zimtrade.co.zw/',         grantUrl:'https://www.zimtrade.co.zw/',        numbeoCity:'Harare' },
];

const combined = [...existing, ...african];
writeFileSync('./faro_AI_web_research_agent/target_cities.json', JSON.stringify(combined, null, 2));
console.log(`Total: ${combined.length} cities (US: ${existing.length} + Africa: ${african.length})`);
