-- MySQL schema for Faro (no Prisma required).

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `ChatMessage`;
DROP TABLE IF EXISTS `ChatSession`;
DROP TABLE IF EXISTS `ComparisonCity`;
DROP TABLE IF EXISTS `Comparison`;
DROP TABLE IF EXISTS `FavoriteCity`;
DROP TABLE IF EXISTS `SavedSearch`;
DROP TABLE IF EXISTS `Report`;
DROP TABLE IF EXISTS `Notification`;
DROP TABLE IF EXISTS `SocialPost`;
DROP TABLE IF EXISTS `SocialAccount`;
DROP TABLE IF EXISTS `Story`;
DROP TABLE IF EXISTS `PasswordResetToken`;
DROP TABLE IF EXISTS `Session`;
DROP TABLE IF EXISTS `UserProfile`;
DROP TABLE IF EXISTS `Grant`;
DROP TABLE IF EXISTS `CityIncentive`;
DROP TABLE IF EXISTS `CityIndustry`;
DROP TABLE IF EXISTS `CityHighlight`;
DROP TABLE IF EXISTS `City`;
DROP TABLE IF EXISTS `User`;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `User` (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(191) NOT NULL,
  name VARCHAR(191) NULL,
  password VARCHAR(191) NOT NULL,
  chatCredits DECIMAL(10,2) NOT NULL DEFAULT 10.00,
  plan ENUM('free','pro','max') NOT NULL DEFAULT 'free',
  planRenewsAt DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY User_email_key (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `UserProfile` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  businessName VARCHAR(191) NULL,
  stage ENUM('IDEA', 'EARLY_REVENUE', 'GROWTH', 'SCALING') NOT NULL DEFAULT 'IDEA',
  industry VARCHAR(191) NULL,
  relocationWindow VARCHAR(191) NULL,
  budgetRange VARCHAR(191) NULL,
  priorities JSON NULL,
  currentLocation VARCHAR(191) NULL,
  relocationNotes TEXT NULL,
  responseStyle VARCHAR(191) NULL,
  language VARCHAR(191) NULL DEFAULT 'en',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY UserProfile_userId_key (userId),
  CONSTRAINT UserProfile_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Session` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  token VARCHAR(191) NOT NULL,
  ipAddress VARCHAR(191) NULL,
  userAgent VARCHAR(191) NULL,
  expiresAt DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY Session_token_key (token),
  KEY Session_userId_idx (userId),
  CONSTRAINT Session_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PasswordResetToken` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  tokenHash CHAR(64) NOT NULL,
  expiresAt DATETIME NOT NULL,
  usedAt DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY PasswordResetToken_userId_idx (userId),
  UNIQUE KEY PasswordResetToken_tokenHash_key (tokenHash),
  CONSTRAINT PasswordResetToken_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `City` (
  id INT NOT NULL AUTO_INCREMENT,
  slug VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  state VARCHAR(191) NOT NULL,
  country VARCHAR(191) NOT NULL,
  region VARCHAR(191) NOT NULL,
  regionCode VARCHAR(191) NOT NULL,
  population INT NULL,
  medianIncome INT NULL,
  costIndex FLOAT NULL,
  businessScore FLOAT NULL,
  blackPopulationPct FLOAT NULL,
  opportunityScore FLOAT NULL,
  networkStrength FLOAT NULL,
  housingIndex FLOAT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY City_slug_key (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `CityHighlight` (
  id INT NOT NULL AUTO_INCREMENT,
  cityId INT NOT NULL,
  text VARCHAR(255) NOT NULL,
  `order` INT NULL,
  PRIMARY KEY (id),
  KEY CityHighlight_cityId_idx (cityId),
  CONSTRAINT CityHighlight_cityId_fkey FOREIGN KEY (cityId) REFERENCES `City`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `CityIndustry` (
  id INT NOT NULL AUTO_INCREMENT,
  cityId INT NOT NULL,
  name VARCHAR(191) NOT NULL,
  PRIMARY KEY (id),
  KEY CityIndustry_cityId_idx (cityId),
  CONSTRAINT CityIndustry_cityId_fkey FOREIGN KEY (cityId) REFERENCES `City`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `CityIncentive` (
  id INT NOT NULL AUTO_INCREMENT,
  cityId INT NOT NULL,
  title VARCHAR(191) NOT NULL,
  description TEXT NULL,
  url VARCHAR(191) NULL,
  PRIMARY KEY (id),
  KEY CityIncentive_cityId_idx (cityId),
  CONSTRAINT CityIncentive_cityId_fkey FOREIGN KEY (cityId) REFERENCES `City`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Grant` (
  id INT NOT NULL AUTO_INCREMENT,
  cityId INT NOT NULL,
  name VARCHAR(191) NOT NULL,
  deadline DATETIME NULL,
  amount VARCHAR(191) NULL,
  url VARCHAR(191) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY Grant_cityId_idx (cityId),
  CONSTRAINT Grant_cityId_fkey FOREIGN KEY (cityId) REFERENCES `City`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SavedSearch` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  query VARCHAR(191) NOT NULL,
  region VARCHAR(191) NULL,
  sortKey VARCHAR(191) NULL,
  filters JSON NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY SavedSearch_userId_idx (userId),
  CONSTRAINT SavedSearch_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `FavoriteCity` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  cityId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY FavoriteCity_userId_cityId_key (userId, cityId),
  KEY FavoriteCity_cityId_idx (cityId),
  CONSTRAINT FavoriteCity_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE,
  CONSTRAINT FavoriteCity_cityId_fkey FOREIGN KEY (cityId) REFERENCES `City`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Comparison` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  title VARCHAR(191) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY Comparison_userId_idx (userId),
  CONSTRAINT Comparison_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ComparisonCity` (
  id INT NOT NULL AUTO_INCREMENT,
  comparisonId INT NOT NULL,
  cityId INT NOT NULL,
  orderIndex INT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY ComparisonCity_comparisonId_cityId_key (comparisonId, cityId),
  KEY ComparisonCity_cityId_idx (cityId),
  CONSTRAINT ComparisonCity_comparisonId_fkey FOREIGN KEY (comparisonId) REFERENCES `Comparison`(id) ON DELETE CASCADE,
  CONSTRAINT ComparisonCity_cityId_fkey FOREIGN KEY (cityId) REFERENCES `City`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ChatSession` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  title VARCHAR(191) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ChatSession_userId_idx (userId),
  CONSTRAINT ChatSession_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ChatMessage` (
  id INT NOT NULL AUTO_INCREMENT,
  sessionId INT NOT NULL,
  role ENUM('USER', 'ASSISTANT', 'SYSTEM') NOT NULL,
  content TEXT NOT NULL,
  metadata JSON NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ChatMessage_sessionId_idx (sessionId),
  CONSTRAINT ChatMessage_sessionId_fkey FOREIGN KEY (sessionId) REFERENCES `ChatSession`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Notification` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  title VARCHAR(191) NOT NULL,
  body TEXT NULL,
  category ENUM('GRANTS', 'CITY_DATA', 'NETWORK', 'SYSTEM') NOT NULL,
  readAt DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY Notification_userId_idx (userId),
  CONSTRAINT Notification_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Report` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  type ENUM('COMPARISON', 'RELOCATION', 'FUNDING', 'GENERAL') NOT NULL,
  status ENUM('PENDING', 'READY', 'FAILED') NOT NULL DEFAULT 'PENDING',
  payload JSON NULL,
  url VARCHAR(191) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY Report_userId_idx (userId),
  CONSTRAINT Report_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Story` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  title VARCHAR(191) NOT NULL,
  city VARCHAR(191) NOT NULL,
  summary TEXT NOT NULL,
  outcomes JSON NULL,
  body TEXT NOT NULL,
  imageUrl TEXT NULL,
  isPublic BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY Story_userId_idx (userId),
  CONSTRAINT Story_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SocialAccount` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  provider ENUM('X') NOT NULL,
  username VARCHAR(191) NULL,
  accessToken TEXT NOT NULL,
  refreshToken TEXT NULL,
  expiresAt DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY SocialAccount_userId_provider_key (userId, provider),
  CONSTRAINT SocialAccount_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SocialPost` (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  storyId INT NOT NULL,
  provider ENUM('X') NOT NULL,
  status ENUM('PENDING', 'POSTED', 'FAILED') NOT NULL DEFAULT 'PENDING',
  payload JSON NULL,
  error TEXT NULL,
  postedAt DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY SocialPost_userId_idx (userId),
  KEY SocialPost_storyId_idx (storyId),
  CONSTRAINT SocialPost_userId_fkey FOREIGN KEY (userId) REFERENCES `User`(id) ON DELETE CASCADE,
  CONSTRAINT SocialPost_storyId_fkey FOREIGN KEY (storyId) REFERENCES `Story`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
