import "server-only";
import puppeteer from "puppeteer";

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function buildHtml(input: {
  title: string;
  summary: string;
  sections: { title: string; content: string }[];
}): string {
  const sectionsHtml = input.sections
    .map(
      (section) => `
        <section>
          <h2>${escapeHtml(section.title)}</h2>
          <p>${escapeHtml(section.content)}</p>
        </section>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: Georgia, serif; color: #1e1a16; margin: 0; padding: 48px 56px; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  .subtitle { color: #6b6055; font-size: 12px; margin-bottom: 24px; }
  .summary { font-size: 14px; line-height: 1.6; padding: 16px; background: #f6f2ec; border-radius: 8px; margin-bottom: 32px; }
  h2 { font-size: 16px; border-bottom: 1px solid #e5ddd0; padding-bottom: 6px; margin-top: 28px; }
  p { font-size: 13px; line-height: 1.7; }
  footer { margin-top: 48px; font-size: 10px; color: #9a8f80; border-top: 1px solid #e5ddd0; padding-top: 12px; }
</style>
</head>
<body>
  <h1>${escapeHtml(input.title)}</h1>
  <div class="subtitle">FARO Autopilot &mdash; Generated report</div>
  <div class="summary">${escapeHtml(input.summary)}</div>
  ${sectionsHtml}
  <footer>Generated by FARO Autopilot. This report is AI-assisted and should be validated against current sources before use in formal decision-making.</footer>
</body>
</html>`;
}

export async function renderReportPdf(input: {
  title: string;
  summary: string;
  sections: { title: string; content: string }[];
}): Promise<Buffer> {
  const html = buildHtml(input);

  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdf = await page.pdf({
      format: "a4",
      printBackground: true,
      margin: { top: "0", bottom: "0", left: "0", right: "0" },
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}
